### ISSUE TITLE
Duplicate points in Postgres when using pdal writers.pgpointcloud 

### ISSUE THREAD

**Issue by losbaltica** [PDAL/CAPI#14]
I am currently writing a small C# program to upload las to Postgres database using PDAL. 
My JSON pipeline:
```
{
  "pipeline": [
    {
      "type": "readers.las",
      "filename": "sample.laz",
      "extra_dims": "HeightAboveGround=float32"
    },
    {
      "type": "filters.range",
      "limits": "Classification[5:5], Classification[10:10], Classification[14:14], Classification[17:17]"
    },
    {
      "type": "filters.chipper",
      "capacity": 600
    },
    {
      "type": "writers.pgpointcloud",
      "connection": "host='localhost' dbname='test' user='postgres' password='123456' port='5432' ",
      "schema": "test",
      "table": "sample",
      "compression": "dimensional",
      "output_dims": "X, Y, Z, Classification, GpsTime, HeightAboveGround"
    }
  ]
} 
```

When executing Pipeline through EXE I am getting a different number of dimensions to compare to executing pipeline from CAPI.
![image](https://user-images.githubusercontent.com/15888155/104744309-a1455400-5744-11eb-8535-e7e03de694b9.png)

Does anyone know the reason why the dimensions get duplicated or observe similar behave?

**Comment by runette** [comment]
At a very, very first glance, it looks like the c# version has every
dimension twice. The first question I would ask is for you to attach the c#
code you are using so we can see what you are reporting on.

**Comment by losbaltica** [comment]
I am using exactly the same CAPI sample classes provided - [sample](https://github.com/PDAL/CAPI/tree/master/csharp)

Then in C# I am calling it as follow: 

```C#
public void ImportLazToPostgres()
{  
     PdalConfiguration.ConfigurePdal();        
     var importPipe = File.ReadAllText("pipeline.json");
     using var pipe = new Pipeline(importPipe);
     pipe.Execute();    
 }
 ```

**Comment by runette** [comment]
That is executing the pipeline - but how are you fetching the result and producing the text that you copied into the issue.

**Comment by runette** [comment]
BTW - an exemplar for using the C# classes to inspect a point cloud is this : 

https://github.com/Simverge/pdal-unity/blob/master/Assets/PointCloudInspector.cs

Although this is designed for Unity - there is nothing specific to Unity about this code (except the `Debug.Log` command). I have used this code myself and do not find it reporting the wrong number of dimensions.

**Comment by runette** [comment]
Sorry - just actually read your pipeline. I understand now. 

No idea. @jimmysoda might but I don't see how it could be down to CAPI - it just passes the pipeline string to PDAL.

**Comment by losbaltica** [comment]
Yea, other pipelines which I was testing was working fine. Is just something with Postgres import. Not sure if the issue is with CAPI or maybe is deeper in PDAL.dll's. However, when I run pdal.exe from the same folder with pdal.dlls, with the same pipeline, dimensions seem to not be duplicated. The other interesting behaviour I noticed is that when I query for a single dimension in PG, I am getting a single correct result. A number of points are correct too. Maybe there is some metadata underneath which gets corrupted when calling pipeline directly from CAPI or rather dll.  

```SQL
SELECT pc_get(PC_Explode(pa), 'HeightAboveGround') pt
FROM test.sample LIMIT 1;
```

![image](https://user-images.githubusercontent.com/15888155/104770974-5f7ad480-5769-11eb-9736-79fd12ad84b7.png)

**Comment by runette** [comment]
You might want to ask the PDAL community

https://lists.osgeo.org/mailman/listinfo/pdal

**Comment by losbaltica** [comment]
Thanks, I will raise it against [PDAL](https://github.com/PDAL/PDAL/issues/3336) team. Let's see what they will say 😄

**Comment by runette** [comment]
Closing because https://github.com/PDAL/PDAL/issues/3336 is closed
