### ISSUE TITLE
Create a conda-forge package for pdal-c

### ISSUE THREAD

**Issue by jimmysoda** [PDAL/CAPI#3]
@hobu recommended creating a conda-forge package to distribute the PDAL C API:

> A conda-forge package might also be another convenient way to distribute a binary. The official PDAL binaries are now on conda to give us good dependency coverage and easy user on-boarding.

_Originally posted by @hobu in https://github.com/PDAL/CAPI/issues/1#issuecomment-455706176_

Follow [conda-forge](https://conda-forge.org/#add_recipe)'s instructions on how to add a _recipe_:
* Fork [conda-forge/staged-recipes](https://github.com/conda-forge/staged-recipes)
* Add a _pdal-c_ recipe in the _recipes_ directory
* Create a pull request to merge the new recipe to [conda-forge/staged-recipes](https://github.com/conda-forge/staged-recipes)
* Make sure that a _pdal-c_ _feedstock_ is automatically added to [conda-forge/feedstocks](https://github.com/conda-forge/feedstocks) after the _pdal-c_ recipe is merged to [conda-forge/staged-recipes](https://github.com/conda-forge/staged-recipes)

_Edited to fix conda-forge/feedstocks hyperlink_

**Comment by runette** [comment]
I want to attempt to make this work - it would be very useful for my project.

But to do that - I need you to create an up to date release and to have some sort of release process in the future (or to give me rights to do that)

Paul

**Comment by jimmysoda** [comment]
Thanks @runette - I don't seem to have admin privileges in this repository. Perhaps @hobu can add you as a maintainer?

**Comment by runette** [comment]
Thanks to @hobu - looks like I have access.

Will look at it over the next couple of days.

Does anyone have any preference over release version numbers. It looks like there were two previous releases in 2019 where the version numbers were synched to the PDAL version. That is a bit clumsy since the dev cycles are not in synch.  I don't want to go backwards from those previous releases so I am tempted to just start with pdal-c v2.0.0?

**Comment by hobu** [comment]
> Does anyone have any preference over release version numbers. 

Pick something that doesn't directly track with the main PDAL release numbers would be my suggestion. It took us a bit to break the convention for Python, but it is much clearer to communicate relationships when the numbers are different and not synched.

**Comment by runette** [comment]
+1

**Comment by runette** [comment]
Just to close this off - now working

see https://anaconda.org/conda-forge/pdal-c

The conda package includes a tool called `test_pdalc` (a cut down version that requires not test data).  This confirms that that the config is correct and reports the version of PDAL it is connected to.

**Comment by hobu** [comment]
https://twitter.com/pointcloudpipe/status/1320720384170381312?s=20 🙏  Thanks so much guys.
