### ISSUE TITLE
Possible Bug - Compile error on std::min

### ISSUE THREAD

**Issue by runette** [PDAL/CAPI#4]
**Describe the bug**
To be honest - I don't know if this is a bug or a config error on my side.

When I tried to compile capi (using make.bat) I got compile errors on pdalc_pipeline.cpp and pdalc_pointview.cpp wherever `std::min` is used, similar to :

```
C:\Users\runes\Documents\GitHub\capi\source\pdal\pdalc_pipeline.cpp(150,35): error C2589: '(': illegal token on right s
ide of '::' [C:\Users\runes\Documents\GitHub\capi\build\x64-windows\source\pdal\pdalc.vcxproj]
C:\Users\runes\Documents\GitHub\capi\source\pdal\pdalc_pipeline.cpp(150,35): error C2062: type 'unknown-type' unexpecte
d [C:\Users\runes\Documents\GitHub\capi\build\x64-windows\source\pdal\pdalc.vcxproj]
C:\Users\runes\Documents\GitHub\capi\source\pdal\pdalc_pipeline.cpp(150,35): error C2059: syntax error: ')' [C:\Users\r
unes\Documents\GitHub\capi\build\x64-windows\source\pdal\pdalc.vcxproj]
```

The solution I found was to add 

```
undef min
```

to each file, suggesting that something is masking  `min` somewhere. As I say - I do not know if it is a config on my side or not.

**Comment by jimmysoda** [comment]
Thanks @runette. I suspect the problem may be a missing include (`<algorithm>`) in each file. I hope to have some free time next weekend to take a look.

**Comment by runette** [comment]
I have put a patch for this in the Conda PR #6

**Comment by runette** [comment]
Re-opened as suggested pending long term solution

**Comment by runette** [comment]
I found the problem - I will create a more permanent solution 

https://stackoverflow.com/questions/5004858/why-is-stdmin-failing-when-windows-h-is-included

**Comment by abellgithub** [comment]
In PDAL we use macro suppression for this:

`(std::min)(foo, bar)`
