### ISSUE TITLE
c# wrapper 

### ISSUE THREAD

**Issue by runette** [PDAL/CAPI#7]
The repo https://github.com/Simverge/pdal-unity includes a C# wrapper for the C API.

Although this is advertised just a demo, they work very well and are the basis for what we are using in our project.

I would like to copy those scripts into this project on an "information only, as an example, not supported" basis.

However - since they are copyright @jimmysoda I would like your comment.

**Comment by jimmysoda** [comment]
@runette Feel free to incorporate Simverge/pdal-unity in any of your projects or as a new repository in https://github.com/PDAL. The license (https://github.com/Simverge/pdal-unity/blob/master/LICENSE.md) allows it. This license is already at the start of each C# source file, so just make sure that information is retained.

**Comment by runette** [comment]
SGTM
