### ISSUE TITLE
Create GH-Pages

### ISSUE THREAD

**Issue by runette** [PDAL/CAPI#8]
@hobu 

I need one more thing - to allow the docs to be hosted by GH.

Can you enable GH Pages in the settings for the repo  - connected to the master branch (not gh-pages) and to the /docs source (not root).

Everything else should happen automatically. I am creating a GH Action to auto-update the docs every time there is a new release.

Thanks

**Comment by hobu** [comment]
✅

**Comment by runette** [comment]
All working now - thanks

see https://pdal.io/CAPI/doxygen/html/index.html

**Comment by runette** [comment]
Just to close this down - there is now a GH action that updates the oxygen docs everytime there is a new release.
